version: 1.0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
nuget:
  project_feed: true
build:
  verbosity: normal
  publish_nuget: true
